sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

language: php

services:
  - mysql

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - mysql -e 'create database laravel_tags;' -uroot

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
