sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade

language: php

services:
  - mysql

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - mysql -e 'create database laravel_tags;' -uroot

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
